[package]
name = "cargotest"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
colored = "2.0"
termion = "1.5"
log = "0.4"
log4rs = "1.0"